import {
  BackgroundPropType,
  ImageBackgroundProps,
  ImageSourcePropType,
} from "react-native/types";

interface Specs {
  name: string;
  URL: string;
  image: ImageSourcePropType;
  bg: ImageBackgroundProps;
  ClassOverview: string;
  ClassOverviewImg: ImageSourcePropType;
  TalentsImg: ImageSourcePropType;
  BasicRotationImg: ImageSourcePropType;
}

interface Class {
  name: string;
  image: ImageSourcePropType;
  URL: string;
  specs: Specs[];
}

export const classes: Class[] = [
  {
    image: require("../images/Classes/warrior.webp"),
    name: "Warrior",
    URL: "warrior",
    specs: [
      {
        name: "Arms",
        URL: "arms",
        image: require("../images/Classes/Spec/war/arms.jpg"),
        bg: require("../images/Classes/Spec/war/arms.jpg"),
        ClassOverview: "Short description of Arms spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/war/arms.jpg"),
        BasicRotationImg: require(""),
      },
      {
        name: "Fury",
        URL: "fury",
        image: require("../images/Classes/Spec/war/fury.jpg"),
        bg: require("../images/Classes/Spec/war/fury.jpg"),
        ClassOverview: "Short description of Fury spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/war/fury.jpg"),
        BasicRotationImg: require(""),
      },
      {
        name: "Protection",
        URL: "protection",
        image: require("../images/Classes/Spec/war/prote.jpg"),
        bg: require("../images/Classes/Spec/war/prote.jpg"),
        ClassOverview: "Short description of Protection spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/war/protection.jpg"),
        BasicRotationImg: require(""),
      },
    ],
  },
  {
    image: require("../images/Classes/paladin.jpg"),
    name: "Paladin",
    URL: "paladin",
    specs: [
      {
        name: "Holy",
        URL: "holy",
        image: require("../images/Classes/Spec/pala/holy.jpg"),
        bg: require("../images/Classes/Spec/pala/holy.jpg"),
        ClassOverview: "Short description of Holy spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/pala/holy.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Protection",
        URL: "protection",
        image: require("../images/Classes/Spec/pala/prote.jpg"),
        bg: require("../images/Classes/Spec/pala/prote.jpg"),
        ClassOverview: "Short description of Protection spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/pala/protection.webp"),
        BasicRotationImg: require(""),
      },
      {
        name: "Retribution",
        URL: "retribution",
        image: require("../images/Classes/Spec/pala/retri.jpg"),
        bg: require("../images/Classes/Spec/pala/retri.jpg"),
        ClassOverview: "Short description of Retribution spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/pala/retribution.png"),
        BasicRotationImg: require(""),
      },
    ],
  },
  {
    image: require("../images/Classes/hunter.webp"),
    name: "Hunter",
    URL: "hunter",
    specs: [
      {
        name: "Beast Mastery",
        URL: "beast-mastery",
        image: require("../images/Classes/Spec/hunter/bm.jpg"),
        bg: require("../images/Classes/Spec/hunter/bm.jpg"),
        ClassOverview: "Short description of Beast Mastery spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/hunter/bm.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Marksmanship",
        URL: "marksmanship",
        image: require("../images/Classes/Spec/hunter/marks.jpg"),
        bg: require("../images/Classes/Spec/hunter/marks.jpg"),
        ClassOverview: "Short description of Marksmanship spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/hunter/marksmanship.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Survival",
        URL: "survival",
        image: require("../images/Classes/Spec/hunter/surv.jpg"),
        bg: require("../images/Classes/Spec/hunter/surv.jpg"),
        ClassOverview: "Short description of Survival spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/hunter/survival.png"),
        BasicRotationImg: require(""),
      },
    ],
  },
  {
    image: require("../images/Classes/rogue.jpg"),
    name: "Rogue",
    URL: "rogue",
    specs: [
      {
        name: "Assassination",
        URL: "assassination",
        image: require("../images/Classes/Spec/rogue/assassination.jpg"),
        bg: require("../images/Classes/Spec/rogue/assassination.jpg"),
        ClassOverview: "Short description of Assassination spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/rogue/assassination.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Outlaw",
        URL: "outlaw",
        image: require("../images/Classes/Spec/rogue/outlaw.jpg"),
        bg: require("../images/Classes/Spec/rogue/outlaw.jpg"),
        ClassOverview: "Short description of Outlaw spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/rogue/outlaw.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Subtlety",
        URL: "subtlety",
        image: require("../images/Classes/Spec/rogue/subtlety.jpg"),
        bg: require("../images/Classes/Spec/rogue/subtlety.jpg"),
        ClassOverview: "Short description of Subtlety spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/rogue/subtlety.png"),
        BasicRotationImg: require(""),
      },
    ],
  },
  {
    image: require("../images/Classes/priest.webp"),
    name: "Priest",
    URL: "priest",
    specs: [
      {
        name: "Discipline",
        URL: "discipline",
        image: require("../images/Classes/Spec/priest/discipline.jpg"),
        bg: require("../images/Classes/Spec/priest/discipline.jpg"),
        ClassOverview: "Short description of Discipline spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/priest/discipline.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Holy",
        URL: "holy",
        image: require("../images/Classes/Spec/priest/holy.jpg"),
        bg: require("../images/Classes/Spec/priest/holy.jpg"),
        ClassOverview: "Short description of Holy spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/priest/holy.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Shadow",
        URL: "shadow",
        image: require("../images/Classes/Spec/priest/shadow.jpg"),
        bg: require("../images/Classes/Spec/priest/shadow.jpg"),
        ClassOverview: "Short description of Shadow spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/priest/shadow.png"),
        BasicRotationImg: require(""),
      },
    ],
  },
  {
    image: require("../images/Classes/deathknight.webp"),
    name: "Death Knight",
    URL: "death-knight",
    specs: [
      {
        name: "Blood",
        URL: "blood",
        image: require("../images/Classes/Spec/dk/blood.jpg"),
        bg: require("../images/Classes/Spec/dk/blood.jpg"),
        ClassOverview: "Short description of Blood spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/dk/bloog.jpeg"),
        BasicRotationImg: require(""),
      },
      {
        name: "Frost",
        URL: "frost",
        image: require("../images/Classes/Spec/dk/frost.jpg"),
        bg: require("../images/Classes/Spec/dk/frost.jpg"),
        ClassOverview: "Short description of Frost spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/dk/frost.jpg"),
        BasicRotationImg: require(""),
      },
      {
        name: "Unholy",
        URL: "unholy",
        image: require("../images/Classes/Spec/dk/unholy.jpg"),
        bg: require("../images/Classes/Spec/dk/unholy.jpg"),
        ClassOverview: "Short description of Unholy spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/dk/unholy.jpeg"),
        BasicRotationImg: require(""),
      },
    ],
  },
  {
    image: require("../images/Classes/shaman.jpg"),
    name: "Shaman",
    URL: "shaman",
    specs: [
      {
        name: "Elemental",
        URL: "elemental",
        image: require("../images/Classes/Spec/shaman/elemental.jpg"),
        bg: require("../images/Classes/Spec/shaman/elemental.jpg"),
        ClassOverview: "Short description of Elemental spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/shaman/elemental.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Enhancement",
        URL: "enhancement",
        image: require("../images/Classes/Spec/shaman/enhancement.jpg"),
        bg: require("../images/Classes/Spec/shaman/enhancement.jpg"),
        ClassOverview: "Short description of Enhancement spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/shaman/enhancement.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Restoration",
        URL: "restoration",
        image: require("../images/Classes/Spec/shaman/restoration.jpg"),
        bg: require("../images/Classes/Spec/shaman/restoration.jpg"),
        ClassOverview: "Short description of Restoration spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/shaman/restoration.png"),
        BasicRotationImg: require(""),
      },
    ],
  },
  {
    image: require("../images/Classes/mage.jpg"),
    name: "Mage",
    URL: "mage",
    specs: [
      {
        name: "Arcane",
        URL: "arcane",
        image: require("../images/Classes/Spec/mage/arcane.jpg"),
        bg: require("../images/Classes/Spec/mage/arcane.jpg"),
        ClassOverview: "Short description of Arcane spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/mage/arcane.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Fire",
        URL: "fire",
        image: require("../images/Classes/Spec/mage/fire.jpg"),
        bg: require("../images/Classes/Spec/mage/fire.jpg"),
        ClassOverview: "Short description of Fire spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/mage/fire.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Frost",
        URL: "frost",
        image: require("../images/Classes/Spec/mage/frost.jpg"),
        bg: require("../images/Classes/Spec/mage/frost.jpg"),
        ClassOverview: "Short description of Frost spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/mage/frost.png"),
        BasicRotationImg: require(""),
      },
    ],
  },
  {
    image: require("../images/Classes/warlock.jpg"),
    name: "Warlock",
    URL: "warlock",
    specs: [
      {
        name: "Affliction",
        URL: "affliction",
        image: require("../images/Classes/Spec/warlock/affliction.jpg"),
        bg: require("../images/Classes/Spec/warlock/affliction.jpg"),
        ClassOverview: "Short description of Affliction spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/warlock/affliction.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Demonology",
        URL: "demonology",
        image: require("../images/Classes/Spec/warlock/demonology.jpg"),
        bg: require("../images/Classes/Spec/warlock/demonology.jpg"),
        ClassOverview: "Short description of Demonology spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/warlock/demonology.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Destruction",
        URL: "destruction",
        image: require("../images/Classes/Spec/warlock/destruction.jpg"),
        bg: require("../images/Classes/Spec/warlock/destruction.jpg"),
        ClassOverview: "Short description of Destruction spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/warlock/destruction.png"),
        BasicRotationImg: require(""),
      },
    ],
  },
  {
    image: require("../images/Classes/monk.jpg"),
    name: "Monk",
    URL: "monk",
    specs: [
      {
        name: "Brewmaster",
        URL: "brewmaster",
        image: require("../images/Classes/Spec/monk/brewmaster.jpg"),
        bg: require("../images/Classes/Spec/monk/brewmaster.jpg"),
        ClassOverview: "Short description of Brewmaster spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/monk/brewmaster.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Mistweaver",
        URL: "mistweaver",
        image: require("../images/Classes/Spec/monk/mistweaver.jpg"),
        bg: require("../images/Classes/Spec/monk/mistweaver.jpg"),
        ClassOverview: "Short description of Mistweaver spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/monk/mistweaver.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Windwalker",
        URL: "windwalker",
        image: require("../images/Classes/Spec/monk/windwalker.jpg"),
        bg: require("../images/Classes/Spec/monk/windwalker.jpg"),
        ClassOverview: "Short description of Windwalker spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/monk/windwalker.jpeg"),
        BasicRotationImg: require(""),
      },
    ],
  },
  {
    image: require("../images/Classes/druid.jpg"),
    name: "Druid",
    URL: "druid",
    specs: [
      {
        name: "Balance",
        URL: "balance",
        image: require("../images/Classes/Spec/druid/balance.jpg"),
        bg: require("../images/Classes/Spec/druid/balance.jpg"),
        ClassOverview: "Short description of Balance spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/druid/balance.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Feral",
        URL: "feral",
        image: require("../images/Classes/Spec/druid/feral.jpg"),
        bg: require("../images/Classes/Spec/druid/feral.jpg"),
        ClassOverview: "Short description of Feral spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/druid/feral.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Guardian",
        URL: "guardian",
        image: require("../images/Classes/Spec/druid/guardian.jpg"),
        bg: require("../images/Classes/Spec/druid/guardian.jpg"),
        ClassOverview: "Short description of Guardian spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/druid/guardian.jpg"),
        BasicRotationImg: require(""),
      },
      {
        name: "Restoration",
        URL: "restoration",
        image: require("../images/Classes/Spec/druid/restoration.jpg"),
        bg: require("../images/Classes/Spec/druid/restoration.jpg"),
        ClassOverview: "Short description of Restoration spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/druid/restoration.png"),
        BasicRotationImg: require(""),
      },
    ],
  },
  {
    image: require("../images/Classes/demonhunter.jpg"),
    name: "Demon Hunter",
    URL: "demon-hunter",
    specs: [
      {
        name: "Havoc",
        URL: "havoc",
        image: require("../images/Classes/Spec/dh/havoc.jpg"),
        bg: require("../images/Classes/Spec/dh/havoc.jpg"),
        ClassOverview: "Short description of Havoc spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/dh/havoc.png"),
        BasicRotationImg: require(""),
      },
      {
        name: "Vengeance",
        URL: "vengeance",
        image: require("../images/Classes/Spec/dh/vengeance.jpg"),
        bg: require("../images/Classes/Spec/dh/vengeance.jpg"),
        ClassOverview: "Short description of Vengeance spec",
        ClassOverviewImg: require(""),
        TalentsImg: require("../images/Classes/Spec/details/dh/vengeance.png"),
        BasicRotationImg: require(""),
      },
    ],
  },
];
