interface Regions {
  name: string;
  servers: string[];
}

export const regions: Regions[] = [
  {
    name: "US Pacific",
    servers: [
      "Aerie Peak",
      "Anvilmar",
      "Arathor",
      "Antonidas",
      "Azuremyst",
      "Baelgun",
      "Blade's Edge",
      "Bladefist",
      "Bronzebeard",
      "Cenarius",
      "Darrowmere",
      "Draenor",
      "Dragonblight",
      "Echo Isles",
      "Galakrond",
      "Gnomeregan",
      "Hyjal",
      "Kilrogg",
      "Korialstrasz",
      "Lightbringer",
      "Misha",
      "Moonrunner",
      "Nordrassil",
      "Proudmoore",
      "Shadowsong",
      "Shu'Halo",
      "Silvermoon",
      "Skywall",
      "Suramar",
      "Uldum",
      "Uther",
      "Velen",
      "Windrunner",
      "Blackrock",
      "Blackwing Lair",
      "Bonechewer",
      "Boulderfist",
      "Coilfang",
      "Crushridge",
      "Daggerspine",
      "Dark Iron",
      "Destromath",
      "Dethecus",
      "Dragonmaw",
      "Dunemaul",
      "Frostwolf",
      "Gorgonnash",
      "Gurubashi",
      "Kalecgos",
      "Kil'Jaeden",
      "Lethon",
      "Maiev",
      "Nazjatar",
      "Ner'zhul",
      "Onyxia",
      "Rivendare",
      "Shattered Halls",
      "Spinebreaker",
      "Spirestone",
      "Stonemaul",
      "Stormscale",
      "Tichondrius",
      "Ursin",
      "Vashj",
      "Blackwater Raiders",
      "Cenarion Circle",
      "Feathermoon",
      "Sentinels",
      "Silver Hand",
      "The Scryers",
      "Wyrmrest Accord",
      "The Venture Co US",
    ],
  },
  {
    name: "US Mountain",
    servers: [
    'Azjol-Nerub',
    'Doomhammer',
    'Icecrown',
    'Perenolde',
    'Terenas',
    'Zangarmarsh',
    'Kel\'Thuzad',
    'Darkspear',
    'Deathwing',
    'Bloodscalp',
    'Nathrezim',
    'Shadow Council'],
  },
];
